---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install the package "fish"
      ansible.builtin.apt:
        name: fish
        state: latest
      
    - name: Install the package "htop"
      ansible.builtin.apt:
        name: htop
        state: latest
        
    - name: Install the package "docker"
      ansible.builtin.apt:
        name: docker
        state: latest
    
    - name: Install the package "nfs"
      ansible.builtin.apt:
        name: nfs-common
        state: latest
    
    
    - name: Creates directory
      file:
        path: /mnt/Loki_PI
        state: directory

    - name: Mount
      mount:
        path: /mnt/Loki_PI
        src: 192.168.178.150:/volume1/PI3
        opts: bind
        fstype: nfs
        state: mounted
