---
- hosts: all

  become: true
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install the package "fish"
      ansible.builtin.apt:
        name: fish
        state: latest
      
    - name: Install the package "htop"
      ansible.builtin.apt:
        name: htop
        state: latest
        
    - name: Install the package "docker"
      ansible.builtin.apt:
        name: docker
        state: latest
    
    - name: Install the package "nfs"
      ansible.builtin.apt:
        name: nfs-common
        state: latest

    - name: Unconditionally reboot the machine with all defaults
      ansible.builtin.reboot:
    
    
    - name: Creates directory
      file:
        path: /mnt/Loki_PI
        state: directory
    
    - name: Creates directory
      file:
        path: /mnt/Loki_HDD
        state: directory
        
    - name: Mount Loki_PI
      ansible.builtin.shell: sudo mount -t nfs 192.168.178.150:/volume1/PI3 /mnt/Loki_PI
    
    - name: Mount Loki_HDD
      ansible.builtin.shell: sudo mount -t nfs 192.168.178.150:/volume2/LOKI_HDD /mnt/Loki_HDD


    - name: Install required Python libraries
      apt:
        name: python3-pip
        state: present
      when: ansible_os_family == 'Debian'  # Adjust for other package managers

    - name: Install requests module
      pip:
        name: requests
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == 'Debian'  # Adjust for other package managers

    - name: Ensure /mnt/portainer_files directory exists
      file:
        path: /mnt/portainer_files
        state: directory
        mode: '0755'

    - name: Start Portainer Container
      docker_container:
        name: portainer
        image: portainer/portainer
        state: started
        restart_policy: always
        ports:
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /mnt/portainer_files:/data

  
